Set max width for parserRadioButtons and parserCheckboxList.
openwebwork/pg pull request #1128
Opened 2024-09-26 22:59 UTC by somiaj

The feedback button for parserRadioButtons and parserCheckboxList can be pushed outside the problem's div if the choices are too long. This sets a max width for the containing div to ensure the feedback is no longer pushed outside the problem's div boundaries.

2024-10-01 18:15 UTC, pstaabp commented
@somiaj Do you have a same problem that shows this?

2024-10-01 18:22 UTC, somiaj commented
Just make very long choices.

```
DOCUMENT();
loadMacros(qw(PGstandard.pl PGML.pl parserRadioButtons.pl));

$mc = RadioButtons([
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut mollis a purus quis tempus. Nulla rhoncus volutpat ullamcorper. Cras velit nisi, ullamcorper quis vulputate viverra, tempus nec arcu. Nulla facilisi. Ut varius fringilla magna, et sagittis metus hendrerit id. In molestie ex eget viverra blandit. Cras sed tellus ac justo dignissim commodo ut eu tortor. Phasellus facilisis pulvinar pellentesque. Duis lacinia erat sed cursus bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus aliquam placerat ipsum, sed dictum dui ultricies quis. Morbi tincidunt dui eu nisl condimentum vehicula.',
    'Nam eleifend ligula nisl, at venenatis ante gravida eu. Nam placerat cursus eros nec eleifend. Suspendisse potenti. Proin sagittis tempus vehicula. Curabitur quis enim ac neque bibendum fermentum ut in orci. Etiam finibus enim in lorem mollis iaculis. Donec commodo nec leo ut varius. Quisque facilisis tellus ut mi semper, vitae rhoncus massa ornare. In sollicitudin leo a augue auctor auctor.',
    'Donec in leo dui. Phasellus justo ligula, feugiat cursus mollis eu, ultrices pellentesque purus. Nullam vitae congue massa. Maecenas fringilla mauris sit amet lorem ultrices ultricies. Integer mattis, nibh a mattis consequat, velit tortor rutrum nulla, eu placerat quam felis ut sapien. Suspendisse nulla felis, consectetur non est vel, efficitur varius risus. Aenean lobortis eleifend ipsum dignissim convallis. Nam massa purus, dictum in est non, fringilla pulvinar mi. Ut elit quam, tempus vitae commodo et, fermentum vel odio. Mauris nisi ligula, tempus in ante at, viverra pellentesque elit. Mauris a varius mi. Fusce aliquet placerat ipsum nec vestibulum.',
    'Vestibulum convallis diam id molestie aliquam. Pellentesque ultrices quam eget orci pharetra, ac ultrices mauris malesuada. Pellentesque facilisis quam iaculis, vulputate ex a, semper sapien. Mauris volutpat mollis quam in iaculis. Curabitur libero velit, auctor condimentum convallis in, consectetur ac tortor. Integer semper eleifend dolor, vel congue diam. Interdum et malesuada fames ac ante ipsum primis in faucibus. Suspendisse id consectetur justo. Sed tristique mi mi, eu venenatis nisi ultricies sit amet. Praesent sagittis orci vehicula nibh dapibus euismod. In velit sapien, porttitor non tortor vitae, interdum vestibulum ipsum. Fusce gravida, enim eu gravida ultricies, eros felis auctor ex, tempus maximus enim mauris sit amet purus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed massa neque, malesuada ac tellus dignissim, vestibulum suscipit leo. Donec consectetur nulla eget velit mattis dignissim.',
    'Phasellus ut libero eros. Cras quam elit, pellentesque vel feugiat et, dapibus scelerisque risus. Nulla at ante dignissim, aliquam urna id, facilisis magna. In finibus posuere ipsum, vel posuere justo imperdiet et. Donec at nunc ac augue sodales dignissim ut et ligula. Nunc sit amet viverra dui. Pellentesque efficitur non neque nec sollicitudin. Donec placerat ex vitae vestibulum dictum. Fusce non sodales neque. Ut sit amet orci nec dui sollicitudin volutpat. Praesent sagittis orci purus, a laoreet nunc eleifend eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed cursus sed ligula sit amet aliquet. Aenean vitae purus at libero eleifend tempor vel id justo. Nulla maximus venenatis diam, pulvinar ornare urna vulputate eget.',
], 0);

BEGIN_PGML
[_]{$mc}
END_PGML
ENDDOCUMENT();
```

Then click show correct answers or check answers.

2024-10-01 19:09 UTC, pstaabp approved these changes
Looks like this fixes it.

2024-10-21 13:46 UTC, drgrice1 requested changes
These styles should not be added inline in this way.  Instead they should be added to `htdocs/js/Problem/problem.scss`.  Just add above line 182 in that file

```scss
	.radio-buttons-container,
	.checkboxes-container {
		max-width: calc(100% - 1rem - 25px);
	}
```

Also, the `width: fit-content` style is not needed as it is already added in `htdocs/js/Problem/problem.scss` in all of these cases.

2024-10-21 16:15 UTC, somiaj commented
Thanks, commit has been updated.

2024-10-31 15:30 UTC, drgrice1 approved these changes

2024-11-25 11:18 UTC, drgrice1 commented
This has been sitting here for a while with two approvals.  I am merging.

2024-11-25 11:19 UTC, merged