Patches to scaffold.pl so Preview does not modify which sections are open - work in progress
openwebwork/pg pull request #506
Opened 2020-10-29 20:37 UTC by taniwallach

This is at attempt to address the first issue from https://github.com/openwebwork/pg/issues/478 and should be treated as preliminary code.

Patches to:
  - prevent scaffold from opening additional section when Preview of the last open section determines it was all correct, and 
  - prevent scaffold from closing open sections if an answer to a prior section became incorrect and Preview is being run.
  - control switches were added to regulate whether the new behaviors are used or now, but default to using the new behavior.

The current patch uses a hidden form field to provide the server with the "number" of the last scaffold section which was open. It does not have any mechanism to prevent a clever user from tampering with that value. As a result, the current implement can be abused to trick the system into opening additional sections if the value of the hidden field is modified to a large value.

My plan is to fix that by adding additional hidden fields including a (random) "nonce" and a "signature" that verifies (together with some server side state information which should remain constant for the user of a given problem) that these hidden fields were not tampered with. Such an approach may not be 100% secure, but should make it quite hard to abuse these changes.

However, the current draft code already provides the rough functionality I think we would like.

---

Testing - using the PG file in [scaffold-sample-01.zip](https://github.com/openwebwork/pg/files/5460947/scaffold-sample-01.zip)

**Before installing the patch:**
1. Open the problem, and enter answer 1,2 in part 1.
2. Click "Preview My Answers" .
3. Part 2 should open - even though the correct answer to part 1 was not submitted for grading. (No attempt was counted.)
4. Enter answer 1,2 in part 2.
5. Click "Preview My Answers" .
6. Part 3 should open - even though the correct answer to part 2 was not submitted for grading. (No attempt was counted.)
7. Make one of the answers in part 1 incorrect.
8. Click "Preview My Answers" .
9. Parts 2 and 3 should close - even though only a "Preview" was requests.
- The desired behavior would require using "Submit Answers" to get the additional sections to open, and would not close open sections on use of "Preview My Answers" .

**After installing the patch:**
1. Open the problem, and enter answer 1,2 in part 1.
2. Click "Preview My Answers" .
3. Part 2 should **not** open.
4. Click "Submit Answers".
5. Part 2 should now open (and an attempt was used up to get it to open).
6. Enter answer 1,2 in part 2.
7. Click "Submit Answers".
8. Part 3 should open (and an attempt was used up to get it to open).
9. Make one of the answers in part 1 incorrect.
10. Click "Preview My Answers" .
11. Parts 2 and 3 should **remain open** - as the "Preview" did not trigger closing them.
12. Click "Submit Answers".
13. Parts 2 and 3 should close - as a submission was made. and the condition to open them no longer holds.
14. Fixing the answer to part 1 and submitting should reopen both parts 2 and 3 (as part 2 had recorded correct answers).

---

Feel free to see how using
```
     allow_next_section_to_open_on_preview => 1
```
and/or
```
     prevent_close_by_preview => 0
```
change the behavior back to the old behavior, if requests.

2020-10-29 20:49 UTC, taniwallach commented
**Note** the use of scaffolding where some "later" sections are intended to be open before some earlier ones is likely to have issues with this patch. In such cases, the new functionality should probably be disabled using the new control switch options for Scaffold. Support for such usage would probably require storing an array of open section numbers instead of just the number of the last open section. Whether there is sufficient need to consider implementing such can be determined in the future.

2020-10-30 08:25 UTC, taniwallach commented
I have been thinking some about this.

1. I think that the "security risk" of having `prevent_close_by_preview` default to 1, which would allow "hacking" hidden value to force all sections open outweighs the intended benefit of preventing sections from closing on Preview when a prior sections answers are damaged. I will change the default in a future commit. For testing, once that is done - the test file will need to be replaced to set it to 1 to have the behavior intended for testing.
2. I think that the "security risk" of having `allow_next_section_to_open_on_preview` default to 0, and of "hacked" input being able to open the next section using Preview of correct answers, without a submission be required is not that bad - it is essentially what happens now, but requires the hack to occur.
3. For the long term, I think we should try to create a mechanism for securing state parameters like this in a tamper resistant manner.
    - I envision a local "API" in PG using which PG code can:
        - set a key to a value,
        - retrieve the value from the current submission (with the back-end code checking that the tamper resistance guarantee is satisfied
    - The API would:
        - "envelop" all the necessary information including the "nonce" and the digital signature into something put into a hidden field (or a cookie, or something else) when a problem is generated, and 
        - handle the parsing / tamper check, etc. and provide the data back to PG when needed.
    - Using an API would allow the technology proving the feature to be modified with no need for problem code to be aware of it.
    - Maybe JWT (JSON Web Token) https://jwt.io/introduction/ is a suitable technology for the initial implementation. (This technology was mentioned in a recent Zoom meeting as being something considered to help interface LibreTexts to WW.)

2021-02-26 13:15 UTC, drgrice1 requested changes
You have this set up to change the defaults to the new behavior that you are introducing.  That should not be the case.  There are instructors out there that depend on this default behavior.  In fact @drdrew42 uses scaffolds in this way.  His point is that he wants students to be able to use the preview button to work through the problem without ever having hit submit until all answers are entered.  He wants this as it pertains to a certain achievement that tracks incorrect submissions.  With your new settings the only way to progress to the next section is to hit submit and get that part correct.  That means the unanswered latter parts are incorrect, and this achievement will note that.

2021-03-08 15:46 UTC, taniwallach commented on macros/scaffold.pl
> +
Correct, changing the default and the documentation.

2021-03-08 15:47 UTC, taniwallach commented on macros/scaffold.pl
> +disables it. Changing the setting to 1 will enable the old behavior.
Done + default being changed to default to the pre-existing behavior.

2021-03-08 15:47 UTC, taniwallach commented on macros/scaffold.pl
> +  my $lastOpen = $self->{open}->[-1];
Being fixed in the next commit.
Thanks!

2021-03-08 15:47 UTC, taniwallach commented on macros/scaffold.pl
> +    allow_next_section_to_open_on_preview => 0,   # control whether Preview My Answers should be allowed to open a new section
Done in the new commit.

2021-03-08 15:48 UTC, taniwallach commented on macros/scaffold.pl
> +    prevent_close_by_preview => 1,                # control whether Preview My Answers should be allowed to close something which was open
Done in the new commit.

2021-03-08 17:20 UTC, taniwallach commented
This was originally posted as a proof of concept, but now that the defaults keep the existing behavior unchanged, the only reason to defer merging it is the hidden issue that tampering with the hidden form field can make trouble. Fixing that requires some method of preventing such tampering which is not something I think I can have ready in time for the release candidate of PG 2.16. As such I have marked this as `deferred`. If people are comfortable with that risk, the current version can be merged, and improvements can be made later.

2023-04-11 12:47 UTC, pstaabp commented
@taniwallach Do we want to revisit this to get into 2.18? If so, need to fix the conflicts.

2023-04-19 13:28 UTC, taniwallach commented on macros/core/scaffold.pl
> +	$self->{isPreview}     = undef;
Fixed. Thanks.

2023-04-19 13:36 UTC, taniwallach commented
I need to fix this for a change made in https://github.com/openwebwork/pg/pull/809 so it is marked as not ready to merge.
The missing change will not impact testing.

2023-04-20 16:33 UTC, taniwallach commented
I made some additional changes so that when a MultiAnswer is in an unopened section and is using `singleResult => 1` then the preview of the first section will not reveal structural information about the answer in the second section. This is a somewhat related flaw in `scaffold.pl` when used with such a MultiAnswer at present.

To see the behavior I think is not correct do a preview of the problem attached below (using a student account, not an instructor account) without the second section being opened before the changes of the second commit (or commenting out the line which sets `scaffold_past_open` in `macros/core/scaffold.pl`). In that case, the preview is "leaking" a hint that there are 2 vectors in the basis in part 2.

With the new changes, that does not occur.

Right now the new code sets `scaffold_past_open` in all answer hashes past the "last open" section, and `parsers/parserMultiAnswer.pl` was modified not to set values for `preview_latex_string` and `preview_text_string` if that is set.

@drgrice1 Do you have a better idea for how this can be done. 

---

There are 2 local files to use with the sample problem. All files were renamed to end with `.txt` to GitHub allows them.

Files:
  - [find_dim_basis.pg.txt](https://github.com/openwebwork/pg/files/11288199/find_dim_basis.pg.txt)
  - [CustomBasisChecker_Rows.pl.txt](https://github.com/openwebwork/pg/files/11287657/CustomBasisChecker_Rows.pl.txt)
  - [rank.pl.txt](https://github.com/openwebwork/pg/files/11287671/rank.pl.txt)

---

Note: The `rank.pl` and custom basis checker file relate to https://github.com/openwebwork/pg/issues/409 and if we can decide how to add `rank.pl` (or nicely add the rank function to the Matrix MathObject in some other manner) and revise the basis checkers for the new release that would be nice. I have modified versions of the various basis checkers.

A version of the problem which demonstrates the bug in code based on the current basis checker (marking incorrect answers as correct) is in:
  -  [find_dim_basis_bug.pg.txt](https://github.com/openwebwork/pg/files/11288114/find_dim_basis_bug.pg.txt)
An incorrect answer in part 2 which gets marked as correct due to the bug is

1,2,1,2
sqrt(253),  2sqrt(253),  sqrt(253),  0.001+2sqrt(253)

---

It seems that there may be problems with the new features in this PR if a problem has answer blanks in an "always open" section which come after sections which are only open when the prior section was correct. I think not supporting that sort of use case for the features added is a relatively reasonable limitation.

2023-04-21 13:36 UTC, pstaabp commented
With this branch, when I first encounter a problem, I'm getting the following error:
```
Use of uninitialized value $prior_last_open in numeric gt (>) at line 470 of [PG]/macros/core/scaffold.pl.
```
I think this is because there is no data in the `problem_data` field of the user problem.   After the first time through, it works.  Perhaps we need a default value for `$prior_last_open` around line 448 of scaffold.pl

2023-04-22 19:32 UTC, taniwallach commented
> prior_last_open

@pstaabp I think I fixed that. I had moved some things around when working on the changes for multianswer but only tested on an old problem so did not see that error, and do not think I ever saw anything like that with the earlier versions of the branch.

Could we try to merge the two PRs about `PERSISTENCE_HASH` data on which this depends before we finish up this one. It became quite tedious updating this PR with the changes made to get https://github.com/openwebwork/pg/pull/809 ready for review and to fix the issues/feedback there.

2023-04-25 17:43 UTC, pstaabp commented
@taniwallach If you make changes to #506, you can then rebase this branch onto that.

The latest commit seems to have fixed the error I was seeing before.

2023-04-25 17:43 UTC, pstaabp approved these changes

2023-04-25 22:11 UTC, taniwallach commented
I have been rebasing, possible not in an efficient manner. Right now this is built on the most recent version of https://github.com/openwebwork/pg/pull/809.

2023-04-25 22:14 UTC, taniwallach commented
@pstaabp Before you approved did you have  a look at the changes to MultiAnswer preview handling for the `singleResult => 1` case? That was a pretty new addition to this PR.

2023-04-28 11:56 UTC, drgrice1 reviewed
I mentioned that I don't like how in https://github.com/openwebwork/webwork2/pull/1940 the `problem_data` field is set even when answers are not submitted.  I still don't think that is a good idea, and I am rather certain that  what you are trying to accomplish in this pull request can be done without that.  Furthermore, I think that there is a way to do this that doesn't even use the database.  This causes rather inconsistent behavior when rendering problems in many of the various different ways that problems can be rendered.  Your new `problem_data` behavior was not implemented for the `render_rpc` or `html2xml` endpoints, it doesn't take into account instructor status, and in general does not seem to be fully thought out.  There are other macros that preserve state without this `problem_data` database column, and I am certain that what you are trying to accomplish can be done using similar techniques.  Both Geogebra applets and MathQuill do that sort of thing using hidden inputs and the `KEPT_EXTRA_ANSWERS` hash.  The problem is that this is saving state and making it persistent in some cases where state should not be persistent.

When an instructor opens a scaffold problem in an assignment, then the "Check Answers" button is available and furthermore scaffolds can be manually opened by the instructors.  This is not taken into account in what is done here, and results in some rather odd behavior of scaffolds.   With or without this pull request and using your first sample problem (scaffold-sample-01.pg), if the instructor opens a later section, answers it correctly (other sections are left unanswered), and clicks "Check Answers", then that section comes back open and that section is colored green.  The difference is in what happens if you next click "Preview My Answers".  Without this pull request if you click preview then that last correctly answered section comes back still open and colored green.  With this pull request, that section is closed and colored yellow.  Only the first unanswered section is now open.

If the instructor is testing the problem on the homework set detail page or in the PG problem editor the new database column is not used, and completely different behavior is exhibited.

Another problem here is that this is just adding to the list of things that scaffold.pl does that are problem authoring decisions, that really should be instructor decisions.  We have discussed this already several times during our meetings.  Ultimately it is very confusing for a problem author what all of the options are and do that control when a scaffold is open or not.  This is further compounded by the fact that authors are going to be testing the problem initially when writing the problem in either the PG problem editor or as an instructor, and the behavior will be inconsistent with what the student will see later in an actual set.

I think in general we need to have more discussion about what is really desired for scaffold behavior, and talk about a good way of implementing it that gives better consistency.  I think that the saving of the `problem_data` column should be rewritten to not occur unless answers are actually being saved.  Although, I think we also need to review the `KEPT_EXTRA_ANSWERS` and `PERSISTENCE_HASH`.  Are they both needed?

As to your changes for parserMultiAnswer.pl problems, that doesn't seem to be working.  I tested this both as an instructor and as a student, and I see the same behavior.  If "Preview My Answers" is clicked on your `find_dim_basis.pg` problem, the results table still reveals information about the second part of the problem.  In fact I see no difference at all for the behavior with or without this pull request.

2023-04-28 11:56 UTC, drgrice1 commented on macros/parsers/parserMultiAnswer.pl
> +	$hide_preview = 1 if ($ans->{scaffold_past_open});
Why does this need to be here in this convoluted format?

2023-04-28 11:56 UTC, drgrice1 commented on macros/parsers/parserMultiAnswer.pl
> +		if ($hide_preview) {
Why can't this just be `if ($ans->{scaffold_past_open}) {`, with the part above deleted?  (Although I don't think any of this is working anyway.)

2025-02-11 20:21 UTC, pstaabp commented
closed now that #1165 is merged.

2025-02-11 20:21 UTC, closed without merging