update the POD for PGauxiliaryFunctions.pl
openwebwork/pg pull request #571
Opened 2021-04-27 17:29 UTC by pstaabp

This updates the POD for PGauxiliaryFunctions.pl, which was not in the correct format to be able to be parsed correctly. 

To test run `WEBWORK_ROOT/bin/dev_scripts/generate-ww-pg-pod.pl` to see the output in html format.

2021-04-27 20:09 UTC, drgrice1 approved these changes
Looks good.  This is much better than just fixing bad formatting the POD in this file previously had.  This actually makes it useful.

2021-04-27 20:29 UTC, drdrew42 reviewed
Just a bunch of tiny edits...

2021-04-27 20:29 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +returns the step function (or Heavyside function) with jump at x=0.  That is when x<0, it returns 0, when x>=0 the function returns 1.
nit: "Heaviside" -- named for Oliver Heaviside... (another instance on L66)

2021-04-27 20:29 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +=head3 gcf function
this is for `gcd`, not `gcf`

2021-04-27 20:29 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +returns the greatest common denominator of the array @arr of integers.
greatest common _divisor_ (not denominator)

2021-04-27 20:29 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +	gcf(20,30,45) returns 5.
not an example of using `isPrime`

2021-04-27 20:29 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +returns the string preformated with the $scalar as 0,1, or -1  takes a number and fixed object, as in "$a x" and formats
pre-formatted (two 't's)

2021-04-27 22:12 UTC, drdrew42 requested changes
I learned a ~~new~~ [github thing](https://haacked.com/archive/2019/06/03/suggested-changes/).

2021-04-27 22:12 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +returns the step function (or Heavyside function) with jump at x=0.  That is when x<0, it returns 0, when x>=0 the function returns 1.
```suggestion
returns the step function (or Heaviside function) with jump at x=0.  That is when x<0, it returns 0, when x>=0 the function returns 1. 
```

2021-04-27 22:12 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
>  sub step {     # heavyside function (1 or x>0)
```suggestion
sub step {     # heaviside function (1 or x>0)
```

2021-04-27 22:12 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +=head3 gcf function
```suggestion
=head3 gcd function 
```

2021-04-27 22:12 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +returns the greatest common denominator of the array @arr of integers.
```suggestion
returns the greatest common divisor of the array @arr of integers.  
```

2021-04-27 22:12 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +	gcf(20,30,45) returns 5.
```suggestion
	isPrime(1337) returns 0.
```

2021-04-27 22:12 UTC, drdrew42 commented on macros/PGauxiliaryFunctions.pl
> +returns the string preformated with the $scalar as 0,1, or -1  takes a number and fixed object, as in "$a x" and formats
```suggestion
returns the string pre-formatted with the $scalar as 0,1, or -1  takes a number and fixed object, as in "$a x" and formats
```

2021-04-27 22:14 UTC, drgrice1 commented
Nice.  That is a useful feature.

2021-04-27 22:59 UTC, pstaabp commented
Not sure I'm using GH efficiently, but I think I made all of suggested changes.  Thanks @drdrew42 .

2021-04-28 19:46 UTC, drdrew42 approved these changes

2021-04-28 19:56 UTC, merged