update the names of tmp folders for LaTeX images
openwebwork/pg pull request #718
Opened 2022-09-09 04:18 UTC by Alex-Jordan

This is not important. But recent investigations had me seeing tmp folders with "tikz" in the name that had nothing to do with tikz. This changes that.

2022-09-09 10:43 UTC, drgrice1 requested changes
This is a temporary directory that is deleted as soon as this method is finished.  So the name doesn't matter much at all.  There certainly is no reason to make the name depend on some condition.  Just change "tikz" to "latex" or something.  That works for tikz as well as that is still latex.

2022-09-09 15:50 UTC, Alex-Jordan commented
I force pushed the simpler thing that you suggested.

2022-09-09 16:02 UTC, drgrice1 approved these changes
Looks good. Thanks.

2022-09-19 01:12 UTC, drgrice1 approved these changes

2022-09-19 10:36 UTC, merged